#!/bin/bash

# format to use:
# ./parse-env.sh

echo "Setting ENV VARS"
. ../.env

# REMOVE CARRAIGE RETURNS FROM .env
APP_ENV="${APP_ENV//$'\r'}"
APP_PORT="${APP_PORT//$'\r'}"
DOMAIN_URL="${DOMAIN_URL//$'\r'}"
LOCAL_IP="${LOCAL_IP//$'\r'}"
GITHUB_PAT="${GITHUB_PAT//$'\r'}"
GCLOUD_PROJECT="${GCLOUD_PROJECT//$'\r'}"
GCLOUD_REGION="${GCLOUD_REGION//$'\r'}"
SERVICE_NAME="${SERVICE_NAME//$'\r'}"
WORKER_SERVICE_NAME="${WORKER_SERVICE_NAME//$'\r'}"
SERVICE_ACCOUNT="${SERVICE_ACCOUNT//$'\r'}"
BUCKET="${BUCKET//$'\r'}"
SUPERADMIN_USERNAME="${SUPERADMIN_USERNAME//$'\r'}"
SUPERADMIN_PASSWORD="${SUPERADMIN_PASSWORD//$'\r'}"
DB_HOST="${DB_HOST//$'\r'}"
SOCKET_CONNECTION_NAME="${SOCKET_CONNECTION_NAME//$'\r'}"
DB_ROOT_PASSWORD="${DB_ROOT_PASSWORD//$'\r'}"
DB_PASSWORD="${DB_PASSWORD//$'\r'}"
DB_USER="${DB_USER//$'\r'}"
DB_NAME="${DB_NAME//$'\r'}"
DB_TIER="${DB_TIER//$'\r'}"
MEMORY="${MEMORY//$'\r'}"
WORKER_HOST="${WORKER_HOST//$'\r'}"
CLOUD_TASKS_SECRET="${CLOUD_TASKS_SECRET//$'\r'}"
SMTP_HOST="${SMTP_HOST//$'\r'}"
SMTP_USER="${SMTP_USER//$'\r'}"
SMTP_PASSWORD="${SMTP_PASSWORD//$'\r'}"
KEEP_ALIVE_MINS="${KEEP_ALIVE_MINS//$'\r'}"